### PR TITLE
Remove Interactive Provider

### PR DESCRIPTION
**Pull request by phobologic**
This is in preparation for "protected mode" for stacks, by allowing the
caller of `update_stack` on the provider to choose whether or not to force
interactive mode.

This also rolls back a small diff when we were preparing to use the
interactive provider when using the `diff` command.

### CODE REVIEW

**Comment by danielkza** [comment]
I use the interactive provider for most stacks when I'm developing or updating a blueprint. Does it make sense to allow the stack to force, but still make it possible to enable manually in the command line?

**Comment by danielkza** [comment]
@phobologic Yep, 100% my fault for not reading the code before asking. Removing the duplicate code seems like a great idea.

**Comment by phobologic** [comment]
Thanks!

**Comment by phobologic** [comment]
Thanks folks!

**Pull request merged**
