### PR TITLE
add stacker_bucket_endpoint config option

### PR DESCRIPTION
**Pull request by troyready**
Allows for use with S3 buckets in isolated regions like cn-north-1

Example endpoint retrieved from
http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html#cnnorth_region

### CODE REVIEW

**Comment by phobologic** [comment]
@troyready is there no way to determine this in a more automated fashion?  Like can we automatically choose the right end point based on the region, or do you think it's better to make this more manual?

**Comment by troyready** [comment]
@phobologic good thought. I've added the automatic detection to the pull request.

I tend to over-value config knobs, so I've left the ability to manually override the endpoint as well. I wouldn't be opposed to dropping it though.

**Comment by phobologic** [comment]
So I was wondering how boto handles this, and I think this can be totally automatic with botocore/boto3:

```
>>> from botocore import session
>>> s = session.get_session()
>>> c = s.create_client("s3", "us-west-1")
>>> c._endpoint.host
u'https://s3-us-west-1.amazonaws.com'
>>> c = s.create_client("s3", "us-east-1")
>>> c._endpoint.host
u'https://s3.amazonaws.com'
>>> c = s.create_client("ec2", "cn-north-1")
>>> c._endpoint.host
u'https://ec2.cn-north-1.amazonaws.com.cn'
```

Since the `provider` should have the s3 connection on it, you should be able to do something similar to above with it I believe.  What do you think?

**Comment by troyready** [comment]
@phobologic yeah, that seems much better. Based on my quick reading, it looks like you could just close this and add the region to https://github.com/remind101/stacker/blob/1.0.2/stacker/actions/base.py#L66 ?

**Comment by troyready** [comment]
Closing in favor of #413

**Pull request closed without merging**
