### PR TITLE
Support for profiles (cross region/account support)

### PR DESCRIPTION
**Pull request by ejholmes**
This is based on the RFC in https://github.com/remind101/stacker/wiki/RFC:-Profiles

Closes https://github.com/remind101/stacker/issues/263
Fixes https://github.com/remind101/stacker/issues/277

With this change, you can specify a boto3 profile to use for a given stack. This can be used for cross account/region provisioning and linking of stacks. For example, say you wanted to provision a hot and cold version of an application in multiple regions, you could do something like this:

```yaml
stacks:
- name: vpc-hot
  profile: hot
- name: vpc-cold
  profile: cold
- name: app
  profile: hot
  variables:
    VpcId: ${vpc-hot::VpcId}
- name: app-cold
  profile: cold
  variables:
    VpcId: ${vpc-cold::VpcId}
```

```console
$ echo <<EOF > .aws/config.prod
[profile hot]
region = us-east-1

[profile prod/cold]
region = us-west-1
EOF
```

```console
$ AWS_CONFIG_FILE=.aws/config.prod stacker build prod.env stacker.yaml
```

## TODO

* [ ] Docs around using boto3 profiles with stacker.
* [x] Hooks. Add support for specifying profile?

### CODE REVIEW

**Comment by ralph-tice** [comment]
The RFC uses dashes for delimiters in profile names instead of slashes, which I think is more consistent and uniform -- slash implies a hierarchy to me rather than joining like dash and underscore indicate.

Also the `profile ` prefix specified in the RFC isn't necessary so should be excluded from the example IMO

**Comment by ejholmes** [comment]
> The RFC uses dashes for delimiters in profile names instead of slashes, which I think is more consistent and uniform -- slash implies a hierarchy to me rather than joining like dash and underscore indicate.

Sorry, I guess the RFC is a little ambiguous about this. The RFC isn't really trying to force a convention around how people name their profiles. You can name them however you want, then reference them with `profile: <profile name>`.

> Also the profile prefix specified in the RFC isn't necessary so should be excluded from the example IMO.

This is true, although, if you have a stacker project shared amongst team members, you'll probably want to also share the config file with the named profiles (if you decide to use profiles). But again, this PR doesn't make any assumptions about that, people can use boto3 profiles however they want, based on http://boto3.readthedocs.io/en/latest/guide/configuration.html.

I'll make a note to update the docs on how to use boto3 profiles with stacker, and maybe some recommendations on sharing a common profile config.

**Comment by smverleye** [comment]
> This is true, although, if you have a stacker project shared amongst team members, you'll probably want to also share the config file with the named profiles (if you decide to use profiles).

That just meant you can leave off the actual `profile` from the profile definition, and it's now recommended to do so:
```
[prod-cold]
region: us-west-2
```

FWIW I could definitely get behind this approach, as it would be compatible with our usage. Currently we're doing multiple regions, but with separate stacker executions for each. This would allow, as you say, for usage of xref across regions which would be valuable for many situations.

**Comment by troyready** [comment]
@ejholmes love it!

Is there a way to extend this to minimize the need for setting the `AWS_CONFIG_FILE` environment variable? Maybe another config option to specify its location?

As is this would work well for us, but it'd be nice to minimize the amount of `botocore.exceptions.ProfileNotFound` exceptions that users encounter when checking out a stacker repo.

**Comment by ralph-tice** [comment]
Sorry, the ~/.aws/config file requires the `[profile ` prefix but ~/.aws/credentials doesn't.  I've never really used the ~/.aws/config file.

I don't see how you would share these profiles without also getting into secrets management...

**Comment by ejholmes** [comment]
> Is there a way to extend this to minimize the need for setting the AWS_CONFIG_FILE environment variable? Maybe another config option to specify its location?

@troyready I thought about it, but not sure it should really be the responsibility of stacker. I think it makes more sense to just use the boto3 defaults, and compose stacker with scripts. But I can be persuaded otherwise.

For example, in our stacker repos, there are just `make prod/stage/dev` targets that you can use immediately after checkout that sets everything up correctly.

In our setup, we'd end up doing this:

```make
stage prod dev: %:
	env AWS_CONFIG_FILE=.aws/config stacker build conf/$@.env stacker.yaml
```

> I've never really used the ~/.aws/config file.
> I don't see how you would share these profiles without also getting into secrets management...

@ralph-tice highly suggest reading up on http://boto3.readthedocs.io/en/latest/guide/configuration.html, and [assumable roles](http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html). They're pretty great :).

There's absolutely no need to share credentials, and we're not suggesting that people do this.

**Comment by troyready** [comment]
@ejholmes appreciate the thoughts. I'd really like to avoid the need for a Makefile-type solution, as it doesn't really feel like it solves #277 for me, but I can appreciate the desire for simplicity.

**Comment by ejholmes** [comment]
@troyready just for my own curiosity, why the aversion to wrapping `stacker build` with a script? Presumably, you're already specifying some flags/arguments on the command line (e.g. `.env` file and `stacker.yaml`), so not sure how `AWS_CONFIG_FILE` ends up being any different.

Any suggestions on where you would like this to be configured (e.g. `stacker.yaml` or `.env` file)?

**Comment by troyready** [comment]
@ejholmes it's definitely just a bad "feeling" to me, where all practical uses of stacker need to be wrapped in a script. I like the idea of the config.yml being the language of what to do and where to get information from it.

As you've said, the current state of things don't allow that so what you're providing is all upside. I'm just trying to continuously nudge improvements to ensure feature superiority against Terraform.

**Comment by ejholmes** [comment]
Added a commit to this that adds profile support to hooks, so you can do stuff like this:

```yaml
pre_build:
  - path: stacker.hooks.route53.create_domain
    required: true
    profile: cold
    args:
      domain: ${basedomain}
  - path: stacker.hooks.route53.create_domain
    required: true
    profile: hot
    args:
      domain: ${basedomain}
```

**Comment by smverleye** [comment]
> As you've said, the current state of things don't allow that so what you're providing is all upside. I'm just trying to continuously nudge improvements to ensure feature superiority against Terraform.

So long as you make no attempt to maintain state outside of the provider itself, Stacker will always be superior to Terraform.

> Sorry, the ~/.aws/config file requires the [profile prefix but ~/.aws/credentials doesn't. I've never really used the ~/.aws/config file.

Was not aware of the difference, but personally I just recommend using only the credentials file. Boto has support for the `~/.aws/config` file but at least the Java SDK does not. From https://boto3.readthedocs.io/en/latest/guide/configuration.html

> If you want to interoperate with multiple AWS SDKs (e.g Java, Javascript, Ruby, PHP, .NET, AWS CLI, Go, C++), use the shared credentials file (~/.aws/credentials). By using the shared credentials file, you can use a single file for credentials that will work in all the AWS SDKs.

> I don't see how you would share these profiles without also getting into secrets management...

Indeed, assumed roles is great. We have shared profiles for different accounts and different access levels:

```
[dev]
region         = us-east-1
output         = json
role_arn       = arn:aws:iam::111111111111:role/NormalAccess
source_profile = identity

[dev-admin]
region         = us-east-1
output         = json
role_arn       = arn:aws:iam::111111111111:role/Admin
source_profile = identity

[prod]
region         = us-east-1
output         = json
role_arn       = arn:aws:iam::22222222222:role/Admin
source_profile = identity
```

Then you just have users populate the "identity" profile with actual IAM access keys. Or for bonus security points have a tool that uses Federation/SAML to fetch temporary STS tokens. Regardless, you can then use shared profiles to define appropriate permission level, account and potentially region without publishing any creds in the file.

This is why being able to specify a profile associated with each stack could be nice. If it requires access to IAM or other sensitive resources you could specify that directly on the stack metadata, by configuring it as requiring an elevated privilege role.

**Comment by bwhaley** [comment]
This feature looks like exactly what I need for xref across multiple AWS accounts using assumerole. Looks like it has been stalled out for a bit and I think @ejholmes mention in Slack he's just not gotten back to it. Can I do something to help move it forward? Does it need additional test coverage?

**Comment by ejholmes** [comment]
@bwhaley I think additional functional test coverage with real world use cases is really the only blocker here. This change isn't high on my list of priorities right now, so feel free to pick it up if you want. Would love to get this in, since it could clean up some none-stacker stuff that we have internally.

**Comment by mchristen** [comment]
This branch piqued my interest because I think I have a use case that would benefit from being able to do multi-region/account deployments from a single config file.

I started to rebase this locally and most of the major conflicts are due to the changes brought in to use a global S3 client from the us-east-1 region.

Is there still interest in getting some mileage on this code?

**Comment by ejholmes** [comment]
> Is there still interest in getting some mileage on this code?

I'm definitely planning on picking this up at some time again in the future, it just dropped down on my list of priorities. 

I think the only thing that really prevents this from happening is challenges around the S3 bucket that stacker uses for storing templates, and permissions for cross account stuff. I'm sure that can be worked out though.

**Comment by ejholmes** [comment]
Gonna close this for now. I'll probably pick this up again in the future.

**Pull request closed without merging**
