### PR TITLE
Encrypted rds

### PR DESCRIPTION
**Pull request by mhahn**
depends on the `subcommands` branch

### CODE REVIEW

**Comment by phobologic** [comment]
Looks like there were some test errors?  Any idea about those?

**Comment by mhahn** [comment]
They looked like some random ones in the mocking library. I think that
rebuilding without the cache would fix them but I couldn't do that on
circleci.

**Comment by phobologic** [comment]
I just kicked it off - lets see how it goes.

**Comment by phobologic** [comment]
Looks like it failed again... https://circleci.com/gh/remind101/stacker/18

**Comment by phobologic** [comment]
Maybe an issue with the new mock libraries?

**Comment by mhahn** [comment]
Hmm I'll take a look, I didn't update those

**Comment by phobologic** [comment]
Yeah, it wasn't your update - the mock libraries released 1.1, and our requirement is `mock>=1.0` so it auto-upgraded.

**Comment by phobologic** [comment]
Ok, can you redo this PR without the mass of commits - it's impossible to see the changes.

**Pull request closed without merging**
