### PR TITLE
It's about time we added an AUTHORS file

### PR DESCRIPTION
**Pull request by phobologic**
Thanks everyone :)

### CODE REVIEW

**Comment by phobologic** [comment]
@ttarhan @acmcelwee @troyready @GarisonLotus @discobean @danielkza If you would rather not be in this, let me know. If I forgot anyone, please let me know that too!

**Comment by GarisonLotus** [comment]
No need to use GarisonLotus. You can put me in there as Garison Draper (single "r") 

Thanks!

**Comment by phobologic** [comment]
Oh, and @mhahn @ttaub

**Comment by phobologic** [comment]
Thanks everyone!

**Pull request merged**
