### PR TITLE
update args comment to reflect current syntax

### PR DESCRIPTION
**Pull request by troyready**
Simple comment update -- should prevent confusion and make it easier to copy/paste

### CODE REVIEW

**Comment by phobologic** [comment]
Not sure I understand what the change is here - it looks like its different now than what the comment suggests?

**Comment by troyready** [comment]
As is, it looks like you could just drop the last `#` and do:
```
   - path: stacker.hooks.route53.create_domain
     required: true
     # Additional args can be passed as a dict of key/value pairs in kwargs
     kwargs:
       foo: bar
```
I want to make it more clear that it should be
```
   - path: stacker.hooks.route53.create_domain
     required: true
     # Additional args can be passed as a dict of key/value pairs in kwargs
     args:
       foo: bar
```
(dropping the kw)

**Comment by troyready** [comment]
@phobologic sure thing; should be more clear now

**Comment by phobologic** [comment]
Awesome, thanks a ton!

**Pull request merged**
