### PR TITLE
Move last of hooks to boto3

### LINKED ISSUE #187: boto3 move missed a few things
It looks like the recent boto3  move (in #174) wasn't totally complete - @troyready fixed one of the hooks, but I mistakenly didn't look at the rest of the hooks.  It looks like the boto2 library is still used in these places:

```
stacker/hooks/iam.py
stacker/hooks/ecs.py
stacker/hooks/route53.py
stacker/providers/aws/default.py
stacker/util.py
```

This was found due to tests failing in #185 

(CC: @acmcelwee - if you have a chance to look at it, I'll try to get to it soon otherwise)

### PR DESCRIPTION
**Pull request by phobologic**
Fixes #187

### CODE REVIEW

**Comment by phobologic** [comment]
@acmcelwee @mhahn I'd love some more eyes on this.  I may actually may try to add #191 to this to test out these calls just to feel more comfortable.

**Comment by acmcelwee** [comment]
I didn't test any of them out, but this LGTM.

**Comment by phobologic** [comment]
Cool - I did some manual testing of each of the hooks, and each test case I ran worked out. I'm going to look into doing some mock stuff for it possibly anyway.

**Comment by mhahn** [comment]
👍

**Pull request merged**
