### PR TITLE
Resolves issue #213 - slashes inside variable lookups

### PR DESCRIPTION
**Pull request by ttarhan**
Simple fix to include "/" in the idpattern for the variable template

### CODE REVIEW

**Comment by phobologic** [comment]
Thanks for this - since I haven't had a chance to become super acquainted with the lookups code as much as @mhahn, I'm going to leave it to him to review.

**Comment by mhahn** [comment]
I think we can just change this to something like `^[\$\{\}]` otherwise we'll keep having to add values here.

**Comment by ttarhan** [comment]
@mhahn - changed, but I just made the change quickly online and haven't tested yet.

**Comment by mhahn** [comment]
looks good!

**Pull request merged**
